version: "3"
services:
  mysql:
    image: mysql/mysql-server
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: 'news'
      MYSQL_USER: 'user222'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - database:/var/lib/mysql
  backend:
    image: x-articles-api
    ports:
      - "4000:4000"
volumes:
  database: