version: "3"
services:
  redis:
    image: "redis"
    expose:
      - 6379
    ports:
      - "6379:6379"
  mysql:
    image: mysql/mysql-server
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: 'news'
      MYSQL_USER: 'user222'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - database:/var/lib/mysql
  backend:
    image: node:8
    build: .
    ports:
      - "5000:4000"
    command: "npm run dev"
volumes:
  database: