version: "3"
services:
  mysql:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: news
  backend:
    image: sanson222/x-articles-backend
    ports:
      - "4000:4000"
